### ISSUE TITLE
Pattern based registrations and multiple matching registrations

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#182]
With pattern based registrations, define the behavior when a single call matches more than one of a _Callee's_ registrations or more than one registration in general.

**Comment by konsultaner** [comment]
My first thought was that it should only be allowed if [shared_registration] (https://github.com/tavendo/WAMP/blob/master/spec/advanced/shared-registration.md) is supported. Otherwize the registration should have already send an error. 

But thinking of a message monitoring scenario. I would then register to the very base of my uri-set.

    com.project.procedures.shop.buy-withPayPal
    com.project.procedures.shop.buy-withSomethingElse
    com.project.procedures.shop.deleteFromCart
    com.project.procedures.shop.addToCart
    ...
    com.project.procedures.forum.addComment
    com.project.procedures.forum.somethingElse
    ...

If wanted to track all my shop activities, I would additionally register a

    [
        64,
        612352435,
        {
            "match": "prefix"
        },
        "com.project.procedures.shop"
    ]

Or if I want to track all buy calls, I could register

    [
        64,
        612352435,
        {
            "match": "prefix"
        },
        "com.project.procedures.shop.buy"
    ]

---------------

I could also think of a second way to handle this. Thinking in object-orientation the pattern based registration could be something like a callable abstract. So the router could forward all messages to the pattern based registration until there is a concrete or closer match. If this happens the router would send it to the callee that had the better match. 

---------------

I'm not sure what to prefer but I cannot think of a scenario where the second attempt would make sense. So I would say: send the call to all matches.

**Comment by konsultaner** [comment]
Is this a problem of WAMP or a business logic problem? Imagine you provide the pattern based registration and shared registration to your callees. One Callee registers a concrete procedure like ```com.example.procedure.something``` and also adds a procedure to track all procedure calls with ```com.example.procedure..```. If another callee only adds ```com.example.procedure.something``` and not ```com.example.procedure..```, the wildcard procedure would be call only every second call if the policy was round robin.

I'd say this is a business logic problem...

**Comment by mbonneau** [comment]
For all use cases I can come up with (which I am sure is incomplete), it seems that URI parts are basically becoming arguments to the RPC.

The complexity added by having to figure out how to handle this issue where both the ```CALL``` and the ```REGISTER``` are able to use pattern/prefix-based URIs is too much to make it worth it.

The best solution is not allowing this on ```REGISTER```. Just move the "argument" part of the URI to the arguments. A call:
```[48, 7814135, {}, "com.myapp.manage.47837483.create", [23, 7]]```
would change to:
```[48, 7814135, {}, "com.myapp.manage.create", [47837483, 23, 7]]```

**Comment by DZabavchik** [comment]
@mbonneau The counter argument is the fact that URIs can be used as method of addressing specific client, where variable part of the URI is not an argument but part of the "routing key".

This post does not in any way touch PubSub, this is strictly about the RPC part of WAMP.

Conceptually RPC URIs (up until March 2013 when @oberstet introduced pattern based registrations) served two purposes:
- From router's perspective RPC URI served as "Routing Key"
- From callee's perspective as Invocation ID (Procedure map Key).

With introduction of prefix and wildcard (pattern) based registration URIs got a new role: extra argument, and instead of **being** a routing key, URIs became **containers of** routing key.
- From router's perspective URI can be a routing key itself or part of it is a routing key. 
- From callee's perspective URI contains key to the procedure map, and remaining part(s) can be used as arguments

It is one of the greatest features of advanced profile.  
Wildcard matching provides ultimate flexibility, but requires extreme caution.
Prefix matches on the other hand allow for structured convention-based efficient method of addressing callees.  It can be essential for ad-hoc federation/clustering. Nevertheless it is still a point of contention.

If we take shared registrations out of the equation (load balancing and round robin stuff), and just consider callee addressing (routing)...  Vast majority of concerns about pattern-based registrations that I've came across can be addressed by well-architected business logic, authorizers, etc.  But, there is still a performance concern.  

In absence of clear separation of routing key (discriminator) from "argument" part of the URI, router has to guess, moving the lookup operation away from being O(1) .  I.e. in Crossbar (`router/observation.py`):

```
# a exact matching observation is always "best", if any
        if uri in self._observations_exact:
            return self._observations_exact[uri]

        # "second best" is the longest prefix-matching observation, if any
        # FIXME: do we want this to take precedence over _any_ wildcard (see below)?
        try:
            return self._observations_prefix.longest_prefix_value(uri)
        except KeyError:
            # workaround because of https://bitbucket.org/gsakkis/pytrie/issues/4/string-keys-of-zero-length-are-not
            if u'' in self._observations_prefix:
                return self._observations_prefix[u'']
```

One possible solution is hinting the router about the routing key portion of the URI:
- URL params style `<URI_ROUTING_KEY>`**?**`<URI_ARGS_PART>` 
i.e. `com.example.zone_a.node.2637846.iface_x?math.add2`
or
- namespace style  `<URI_ROUTING_KEY>`**::**`<URI_ARGS_PART>` i.e. `com.example.zone_a.node.2637846.iface_x::math.add2`
or 
- call options hint: `[48, 72836846, {"prefix":"com.example.zone_a.node.2637846.iface_x"}, "com.example.zone_a.node.2637846.iface_x.math.add2", [23, 7]]`

This can bring prefix calls from O(log(n)) back to O(1) realm, and clear concerns about possible abuse of pattern-based registrations.

**Comment by oberstet** [comment]
The original question/issue I had in mind is exemplified exactly in the code linked by @DZabavchik : the FIXMEs in [this](https://github.com/crossbario/crossbar/blob/master/crossbar/router/observation.py#L333).

So it's a matter of defining a **resolution order** for matching.

The (incomplete) proposal is to let a match take precedence over other matches based on "selectivity":

1. an exact match alway has highest priority
2. when there is no exact match, the longest prefix match takes precedence
3. prefix matches always take precedence over any wildcard match
4. when there is neither an exact match, nor a prefix match, take the "most selective" of all wildcard maches

This lacks a definition of "most selective" for wildcard matches. Eg consider these wildcard patterns

1. `com.*.*`
2. `com.*.foo`
3. `com.bar.*`

Given a call to `com.bar.foo`, all 3 patterns above do match, but which one is the "most selective"?

One possibility:

* a wildcard match with more wildcard components is less selective. That would mean, 2. and 3. are more selective than 3.
* a wildcard match that has it's wildcard components in positions further to the end is less selective than one with wildcard components in front. That would mean 3. is more selective than 2.

So we could assign a "matching score" based on number of wildcard components and wildcard component positions.

**Comment by oberstet** [comment]
Regarding performance: when introducing pattern-based subs/regs, we tried to balance pattern flexibility against performance. Eg we deliberately avoid general wildcard patterns (where wildcard are not restricted to URI components) or stuff like regex matching - both can't be done in O(log(N)).

Further I think O(log(N)) is "ok" .. but not slower .. eg O(N * log(N)) or even O(N^2).

IOW: I don't think O(log(N)) isn't a practical performance bottleneck in real-world router implementations and applications (of course one can construct a _synthetic_ scenario where it _might_ be a bottleneck).

**Comment by oberstet** [comment]
Regarding the interplay of above with "shared regs": I think the sharing should be exlusively over the set of "most selective" matching callees, NOT over all matching callees.

**Comment by gammazero** [comment]
@oberstet I agree with your [logic](https://github.com/wamp-proto/wamp-proto/issues/182#issuecomment-191691927) for resolution order for matching.  This is also how my implementation behaves.  To answer the final question, what is the definition of must selective wildcard match, I propose this:

The **most selective** wild card match is the one that has the longest portion before _each_ wildcard.

This rule disambiguates any combination of the following when matching `com.bar.foo`:

- `*.bar.foo`
- `com.*.*`
- `com.*.foo`
- `com.bar.*`

You can see how this continues to work for any length wildcard patterns.  For example, to disambiguate the following when matching `com.bar.foo.baz`:

- `com.*.*baz`
- `com.*.foo.*`

**Comment by oberstet** [comment]
@gammazero yeah, this is a good tie breaker rule. So this completes the original issue I had in mind - I think what @konsultaner discusses is yet another topic? If you agree, I would propose to split that out into a new issue, and consolidate a spec text from the combined comments. I think this is an important piece of detail missing in the spec that should complete the pattern matching stuff. and actually, then there is implementation work to do;)

**Comment by KSDaemon** [comment]
Sorry for (may be) stupid question, guys. Did i miss something?... You all operate with `*` symbol for wildcard URIs (which is more eye-friendly). But in SPEC we use `..` (double dots) notation for specifying wildcard URIs.

**Comment by oberstet** [comment]
@KSDaemon the spec is correct rgd wildcard syntax - I guess people are just so used to `*` as a placeholder that it's used in text ..

**Comment by KSDaemon** [comment]
Please, have a look at PR. I've tried to combine all our thoughts into SPEC

**Comment by KSDaemon** [comment]
So, PR is merged. I'll close this issue.
