### ISSUE TITLE
Basic Spec: Invocation.Request two possible ways of implementation

### ISSUE THREAD

**Issue by bwegh** [wamp-proto/wamp-proto#190]
In the basic spec there are two ways how Invocation.Request can be done:

once following the "IDs" section "Session Scope IDs" which contains "INVOCATION.Request" as "SHOULD be incremented by 1 beginning with 1"

and once following the "INVOCATION" section of "Calling and Invocations" with "Request is a random, ephemeral ID chosen by the Dealer and used to correlate the Callee's response with the request"

I vote for clarifying this and for the first way, incrementing it with each request.

**Comment by meejah** [comment]
FWIW, Crossbar is using sequential IDs. Note that they wrap at 2^53 "because JavaScript".

And yes, defining them as sequential avoids having to then also specify "how random" (e.g. the range) the random numbers need to be to avoid birthday-problem collisions when there are many outstanding invocations. (2^53 is definitely too small in practice for random numbers for this)

**Comment by oberstet** [comment]
@bwegh 

> once following the "IDs" section "Session Scope IDs" which contains "INVOCATION.Request" as "SHOULD be incremented by 1 beginning with 1"

This is how it should be done. The other text is wrong (a bug in the spec . .historically, it was "random IDs").
