### ISSUE TITLE
GOODBYE messages shouldn't use error URIs

### ISSUE THREAD

**Issue by goeddea** [wamp-proto/wamp-proto#192]
At the moment, a regular closing of a WAMP connection sends error URIs such as

"wamp.error.system_shutdown"
"wamp.error.goodbye_and_out"

While not a technical problem, the semantics of this are just wrong. There is no error state here. The spec correctly states that the GOOBYE message sends a reason, and the URI should reflect that, e.g. 

"wamp.closing.system_shutdown"

**Comment by angiolep** [comment]
Also pointed out in https://github.com/wamp-proto/wamp-proto/issues/242

**Comment by KSDaemon** [comment]
Agree with @goeddea. That is not an error. Just some short formal description of process or status or action.
I do not like an idea of some specific words like `.closing.` or `.goodbye.`
My personal opinion is to have something general, like `wamp.message.xxxx`, so we can use it in future without modifying and introducing new namespaces. 
On 2nd place is `wamp.status.xxxx`. But again, "wamp.error.system_shutdown" — is no a status, it's just a text message (reason), describing last action, that peer closed connection.

For now i grep'ed through spec, and i propose next changes:
* wamp.error.system_shutdown → wamp.message.system_shutdown
* wamp.error.goodbye_and_out → wamp.message.goodbye_and_out
* wamp.error.close_realm → wamp.message.close_realm
* wamp.error.goodbye_and_out → wamp.message.goodbye_and_out
* wamp.error.canceled → wamp.message.call_canceled

**Comment by ecorm** [comment]
Other suggestions:

- `wamp.info.*`
- `wamp.goodbye.*`
- `wamp.reason.*`

**Comment by oberstet** [comment]
ok, I agree with a) "normal close" is not an error, and that b) that should be reflected in naming.

however, I'd prefer to common prefixes:

* `wamp.close.error.*`
* `wamp.close.success.*`

That is, 2 classes of prefixes: the common one for all stuff related to "close", and then 2 subprefixes to collect error closing vs normal closing.

**Comment by KSDaemon** [comment]
Hmm... I don't think introducing 3 level deep messages is really needed.
May be just stick to 2:
* `wamp.(message|info).*` — for an informational messages over all WAMP spec
* `wamp.error.*` — for any error messages. 

For example:
* `wamp.error.aborted_by_router`  — for error during closing wamp session by router
* `wamp.message.goodbye_and_out` or `wamp. info.goodbye_and_out` — for normal closing.

**Comment by gammazero** [comment]
@KSDaemon I think the `wamp.error.canceled` message should remain unchanged since that is delivered within and ERROR message.  If we change that, then we start having to decide whether each message is an error, or something more informational.  For example, `wamp.error.no_eligible_callee` could also be considered informational - "It is not an error, there is just no eligible callee".  So, lets not go down that slippery slope.  A URI in an ERROR message should always be in the `wamp.error.` namespace.

The remaining three (`wamp.message.system_shutdown`, `wamp.message.goodbye_and_out`, `wamp.message.close_realm`) are all sent in GOODBYE messages, so it does make sense for them to live in different namespace.

However, I am concerned that a generic namespace like `wamp.message.` or `wamp.info.` will be used as a catch-all for messages that should have a more specific namespace.  Since the three URI's above have to do with closing a session/connection, I suggest putting them in a namespace specific to that:

- wamp.error.system_shutdown → wamp.close.system_shutdown
- wamp.error.goodbye_and_out → wamp.close.goodbye_and_out
- wamp.error.close_realm → wamp.close.close_realm

**Comment by gammazero** [comment]
So to put it another way, each part of the wamp URI namespace should further classify a message.  Namespaces elements like `.info.` or `.message.` do not add any more value since the data is already info; already a message.  Something like `wamp.close.` does add classification since that denotes messages that are specific to closing the session/connection.

**Comment by oberstet** [comment]
I agree with @gammazero here. Two namespaces:

* `wamp.error.` => all errors, and only errors (in an extended interpretation of "error")
* `wamp.close.` => all close reasons, and only those (closing - in any way, under any circumstances)

**Comment by angiolep** [comment]
I also like @gammazero proposal

**Comment by KSDaemon** [comment]
Agree. Please, take a look at #304 PR
