### ISSUE TITLE
Reserved Protocol Violation Error

### ISSUE THREAD

**Issue by theduke** [wamp-proto/wamp-proto#234]
I think the spec should include a generic 'protocol violaton' error that can be used by implementations for reporting some kind of protocol error, for example, an unrecognized messge type, invalid payload, messed up framing with wamp over raw sockets, multiple messages submitted with wamp over longpoll in non-batched mode, the list goes on and on.

"wamp.error.protocol_violation".

Additional information can be included in the details.

Implementations could then decide how to handle protocol violation errors, by either terminating the whole connection (with 'wamp.error.protocol_violation' as the reason), just reporting the error, etc.

**Comment by oberstet** [comment]
There is no "protocol violation" WAMP error URI, since protocol violations like "invalid message type" are fatal, and the peer MUST immediately close the connection - and hence can't send a WAMP level error.

**Comment by theduke** [comment]
Hmm, I guess I missed that part in the spec, where is it mentioned?

Shouldn't a clean shutdown still be tried?
Just closing the connection without reporting an error seems like a bad idea to me.
Also makes debugging harder.

Like: on protocol violations, send a GOODBYE with the reason "wamp.error.protocol_violation" and then terminate the connection.

The websocket protocol works the same way.

**Comment by oberstet** [comment]
> The websocket protocol works the same way.

Please see http://tools.ietf.org/html/rfc6455#page-43. In particular:

> An endpoint MAY omit sending a Close frame if it believes the other
   side is unlikely to be able to receive and process the Close frame,
   due to the nature of the error that led the WebSocket connection to
   fail in the first place.  An endpoint MUST NOT continue to attempt to
   process data (including a responding Close frame) from the remote
   endpoint after being instructed to _Fail the WebSocket Connection_.

Continuing talking to a peer that is either broken or actively attacking can lead to security issues.

> Note: AutobahnPython - at the WebSocket level - has an option to control that behavior: `failByDrop = True|False`.

--

That being said: you are right, relevant text is missing in the spec. The spec at various places talks about "fail the session", but doesn't define what that means=(

My current view is this:

WAMP protocol violations (like wrong type for message type or invalid message type) should be handled with hard-dropping the underlying _transport_ (not only the session) with no feedback at all to the peer, but logging on the other side (the one that fails the session/connection). Reasoning: the peer proofed to be unable to speak WAMP, so why continue to talk WAMP, which might be a risk? As noted, the text is missing for that.

However, the use of invalid URI _values_ should not be a protocol violations, but WAMP level errors ("call with invalid URI"). The use of an invalid type for an URI (like integer, instead of string) is still a protocol violation though.

**Comment by fresheneesz** [comment]
@oberstet I don't think dropping without any attempt to relay the error is unacceptable. Things like that make a developer's life hellish. If something isn't speaking the protocol correctly, that's the fault of the party that incorrectly implemented the protocol, and any risk associated with it is theirs as well. Everyone makes mistakes (even, and possibly especially protocol implementers), and they need the information to be able to correct those mistakes.

**Comment by goeddea** [comment]
@fresheneesz - The peer failing the session should log the reason. This does mean that you need access to both sides of the connection to be able to debug, but you do get feedback about the reason (just no on the side of the peer which made the error).

**Comment by fresheneesz** [comment]
@goeddea I disagree. The peer who received the erroneous message often should *not* log the reason. You can't trust your clients to be errorless, and sometimes that means that you can get thousands of errors from your clients - and that's their problem not yours. Why fill up disk space with errors that you can't do anything about?

Also, on the flip side, the peer who made the error is the very peer that needs an error message telling them what they did wrong in some way. When you say "you do get feedback" you really meant "someone gets feedback". Unfortunately, what you're saying is that the *wrong* party gets the feedback. I doubt it's rare for the client to be a different person than the server.

This is bass ackwards. The peer that made the error should get an error message before being dropped. The peer that received the erroneous message should send a terse error response, ensure it was sent (regardless of whether it was received), then drop the connection.

**Comment by oberstet** [comment]
@fresheneesz there are at least 2 perspectives here: the developer of a WAMP client library, and the operator of a production router.

From a router perspective, the most robust solution is:

* not log anything (because of DoS vector)
* kicking the misbehaving client without much ado or feedback (again, DoS)
* after N misbehavior events, block the client altogether

In "production", I want to run like above.

So the question is more about options to adjust the behavior, and about default behavior (when not setting options).

One school / philosophy goes with "secure by default". That is, "production settings are default". The other school goes like "it just works". Everything open and easy and forgiving by default. There are good reasons for both ..
