### ISSUE TITLE
Namespaces for Authentication Methods

### ISSUE THREAD

**Issue by ecorm** [wamp-proto/wamp-proto#289]
WAMP currently does not make any provision for implementation-specific authmethods. The current authmethod strings cited in the spec are:

- `"anonymous"`
- `"wampcra"`
- `"ticket"`

There is currently nothing in the spec that prevents implementation-specific authmethod strings from clashing with future standard authmethod strings.

The standard authmethod strings should have been prefixed in their own namespace, for example `"wamp.ticket"`, or perhaps `"wamp.authmethod.ticket"`. This would have been more in tune with the way standard error URIs are prefixed.

If it's too late to add a prefix to the standard authmethods, what we can do instead is mandate a prefix for non-standard authmethods. For example, `"custom.com.example.my_auth_method"`, where `custom` is the mandated prefix.

**Comment by ecorm** [comment]
The same problem arises with custom feature strings.

**Comment by oberstet** [comment]
Huh: custom authentication methods .. this goes even further than eg providing "extra/details" to tweak a authentication method (like WAMP-CRA, tweaking the salting algo etc).

I leave that open for discussion, but tbh, I am not fond of the idea, because the authentication methods establish a certain pattern of message exchange, and such.

In general: the whole idea of "fixing" a lot for the authentication methods, instead of providing open negotiation, or even full open auth methods was: avoid the complexity, and resulting pitfalls and bugs that eg TLS implementations plague ...

Plus: I haven't felt a need .. so it would be good to state _why_ you have that need. There will be a tradeoff between flexibility and complexity. And that can only be "judged" based on use cases and their "frequency" (what's the right word here?).

**Comment by meejah** [comment]
My reservations to doing something like this are similar: confusing users as to what a "good" auth method is. That part *should* remain fairly clear: the only "blessed" auth methods are those built-in to crossbar + WAMP.

Another way to look at it is like this: a general "challenge + response" authentication system does seem to cover many existing authentication algorithms (basically anything with one round-trip to the client). IIRC, the protocol does allow for arbitrary number of client round-trips, too. Crossbar + WAMP only support a couple authentication mechanisms currently. If you DO have a use-case that's outside this, you don't have many options (basically: learn Python and fork crossbar.io or try to wedge your use-case into "ticket auth".)

"Wedge into ticket auth" is basically the only mechanism to tie in third-party authentication (e.g. YubiKey/FidoAlliance, LDAP, OAuth, GitHub et al.) Perhaps it would be useful here to enumerate which of these types of use-cases *could* be supported with a general challenge/response API. Having some kind of API for this might allow more experimentation etc with authentication (and any popular, concrete implementations could be "promoted" to a blessed, supported auth method).

Even more useful might be to simply understand what "in the wild" implementations are doing with "ticket auth"...?

**Comment by oberstet** [comment]
I have to agree with @meejah here.

Plus, there is another thing we do actually have a pressing need for (IMO, at least I feel it): multi-factor authentication.

This requires multiple roundtrips: HELLO, CHALLENGE, AUTHENTICATE, CHALLENGE, AUTHENTICATE, ..., WELCOME

eg I would like to be able to do 2-factor auth, WAMP-cryptosign and WAMP-CRA. or WAMP-cryptosign and WAMP-ticket, where the latter is doing TOTP (https://github.com/crossbario/crossbar-examples/tree/master/authentication/ticket/totp)

**Comment by oberstet** [comment]
@ecorm note, I am not trying to brush that off by opening even more can of worms (multi-factor), I just want to make sure, that _if_ we expand this here, we get it "right", in the sense that any solution will not hinder us later for multi-factor ..

**Comment by oberstet** [comment]
plus, I absolutely agree with meejah: we _should_ be  opinionated with authentication methods ("blessed" ones), because we here are probably all able to assess and create safe auth methods - but .. huh, not the general developer (often) .. we _should protect the innocent_;)

an app developer should not be put into a situation where he/she would even think about cooking up sth on their own.

for example, that same philosophy is what NaCl is following: the level of abstraction they provide for crypto primitive makes is _hard_ to fuck it up;) which is good! I like that. It gives me peace in mind .. I don't feel ready to grok all those details under the hood .. so it is welcome from my POV that they _restrict_ me.

**Comment by ecorm** [comment]
@oberstet @meejah At the pace things are moving, you're never going to be able to keep up with the state-of-the art when it comes to authentication. The WAMP-CRA "Pass the Hash" (#128) vulnerability was reported in 2015 and there's still no standard alternative specified today in 2018. There *has* to be a mechanism to allow WAMP adopters to implement their own authorization schemes that meet their business needs, or you're going to lose adopters.

I can't contribute a magic, generic authentication scheme that will suit everyone's needs and be future-proof. But I can implement my own that suits my business needs today **if** the WAMP/Crossbar machinery will let me. I might shoot myself in the foot, but at least I won't be liable if others shoot themselves in the foot by using my generic solution.

Having said that, I'm fairly confident my authentication needs will be met by WAMP (but perhaps not Crossbar) in the foreseeable future by ticket-based auth, under the following conditions:

1. The interpretation of the `AUTHENTICATE.Signature` remains up to the application (as stated in the second paragraph of [14.5.2.4. Ticket-based Authentication](http://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#ticketauth)).
2. I'm allowed to pass application-specific data within `CHALLENGE.Extra` field. This is permitted under [6.1. Extensibility](http://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#extensibility), but currently not supported by Crossbar (see https://github.com/crossbario/crossbar/issues/1244).

What I call "custom authorization scheme" is probably already embodied in ticket-based auth as specified by WAMP (but currently not Crossbar, unless I have a way to send `Challenge.Extra` data).

By all means, keep working on "blessed" auth schemes somewhere down the road, but please don't prevent me from implementing my own **today**.

**Comment by ecorm** [comment]
> an app developer should not be put into a situation where he/she would even think about cooking up sth on their own.

If I had not done my due diligence as an "app developer", and scrutinized the WAMP-CRA method, I would not have known that it's vulnerable to database theft, which is far more likely than a MItM decrypting TLS.

So I'm better off implementing my own auth scheme. The alternatives are to wait for the WAMP community to get its act together when it comes to password security, or go with a different middleware technology that doesn't try to hold my hand security-wise.

**Comment by oberstet** [comment]
> By all means, keep working on "blessed" auth schemes somewhere down the road, but please don't prevent me from implementing my own today.

I get it;) No worries, I am taking this serious (both your itch, and your critics in general)

Pls see the discussion on the other issue touching on "WAMP-generic". However, the only thing we need in the WAMP spec for that would be agreeing on an identifier for that. The rest would be a Crossbar.io feature ..

That being said: I also agree we should have done WAMP-scram long ago ..both in the spec, and in implementation. No argument there (other then the usual .. gimme the resources/money to pull all these things off;)

> you're never going to be able to keep up with the state-of-the art when it comes to authentication

WAMP-cryptosign

> WAMP-CRA "Pass the Hash" (#128) vulnerability 

Please: it's not a "vulnerability", but a limit of what it protects against, and what not.

> If I had not done my due diligence as an "app developer", and scrutinized the WAMP-CRA method

Yes, the bug is in documentation, not documenting the attack scenarios and limits.

_Any_ authentication scheme has limits, and if you call a "limit" a vulnerability, then there is not a single one not vulnerable to some scenario.

Eg take public-private key based methods (TLS client cert, WAMP-cryptosign).

When I get your private key, you are doomed.

Ok, now you might say: don't have the private key on the computer running the client code. Eg use a hardware based module.

This just shifts the boundary (limits): again, there are attacks on that as well.

There is no 100% secure thing. IMO this is super important to realize and _accept_, because otherwise there is a risk you feel too safe, loose paranoia, ..

> eg recently, I stumbled across some (Dilbert?) cartoon .. cant find it now. but the essence: if you think your super duper security crypto is gonna save you from the agencies, they just buy a 10 $ stick and hit you until you give up all your secrets! Thats how it works. if you don't have the practical means of hitting back (unlikely), you will get .. FCKD. this is slightly OT rgd above, but still ..

**Comment by oberstet** [comment]
for the record, WAMP-cryptosign has limits too! not only if the private key is compromised.

eg WAMP-cryptosign has TLS channel binding (!) - name a middleware/implementation that even talks about that.

however, this currently only works with ABPy.

ABJS in browser: no way to implement it currently - the browser JS API simply does not expose the necessary bits.

**Comment by ecorm** [comment]
All is cool. I'm sorry if I sounded a little rude, but I'm under pressure because I took a gamble by adopting WAMP for our commercial project. That being said, I realize there would have been risk involved for **any** technology chosen for our middleware.

All I need is for a router to call my backend's `myapp.make_extra_challenge_info` RPC with the session infomation (at least the session ID), where I can return a custom object that's forwarded via `CHALLENGE.Extra` to the frontend client. You can restrict this feature for only ticket-based auth.

The extra cherry on the cake would be for the dynamic authorizer RPC to receive the `AUTHENTICATE.Extra` object. In the absence of that, I can still make the front-end client encode all the needed information in a string that's passed via the `AUTHENTICATE.Signature` field.

I might be able to muddle through the Python and submit a PR for Crossbar to support my proposed Dynamic Challenger feature, by using the dynamic authorizer code as an example. But we can talk about this in the Crossbar issue tracker instead of here.

**Comment by oberstet** [comment]
> All is cool. I'm sorry if I sounded a little rude, but I'm under pressure because I took a gamble by adopting WAMP for our commercial project. 

Thanks for explaining! We get this addressed - one way or the other. Won't leave you "in the cold" .. however, I need to get some sleep, and I am fully packed for the rest of the week with business trips. if this is super duper urgent, pls check with meejah ..

**Comment by oberstet** [comment]
closing: we now have WAMP-SCRAM properly defined (and implemented in at least AutobahnPython and Crossbar.io)
