### ISSUE TITLE
Add Payload to Abort

### ISSUE THREAD

**Issue by konsultaner** [wamp-proto/wamp-proto#499]
`ABORT` currently only has a message dictionary that is part of the head of the message. If an `ABORT` needs to send rich content or private content to the client receiving the `ABORT`. The message dictionary need to be used at the moment. The problem is that some advanced and custom features like

- opaque payload
- E2E encryption
- zero-copy routing

will be impossible, leading to an unsecure or slow data transfer. Thats why it would be great to have a Payload added to `ABORT`.

**Comment by KSDaemon** [comment]
Interesting question. Yeah I sometimes feel the lack of payload in such cases. And I agree, having other features like e2ee that operate on the payload layer - is a problem for WAMP messages without payload options.

Regarding ABORT - my first thought is that adding a payload kargs and kwargs may be done without much pain, so all current flows should work... But need to think of this more...

**Comment by oberstet** [comment]
yes, indeed interesting angle:

custom content in `ABORT` currently requires use of `ABORT, Details|dict` (so one _can_ send custom content) - **BUT because** there is no `ABORT.args` and `ABORT.kwargs`, that custom content will not be covered under opaque payload, E2E encryption and (possibly) zero-copy routing.

mmh. on the one hand we added `Details` to all WAMP messages to allow custom extensions easily (e.g. for controlling routing), and tbh I _thought_ that should be good enough for extensibility in general .. but it doesn't cover application payloads ...

as also @KSDaemon hints at .. yes, it could be added without lots of pain I guess ... but I think, if so, then we might think about aiming to have `args` and `kwargs` in _every_ WAMP message .. because @konsultaner argumentation applies to not only `ABORT` ?

not sure ... I am just trying to explore the design space and questions ..

**Comment by konsultaner** [comment]
@oberstet whats up next? Should I write a PR?

**Comment by oberstet** [comment]
@konsultaner : so I think the proposal is clear.

The _current_ protocol has `Arguments|list, ArgumentsKw|dict` _only_ for the following messages:

* `ERROR`
* `CALL`
* `RESULT`
* `INVOCATION`
* `YIELD`
* `PUBLISH`
* `EVENT`

and it does NOT have those for the following messages:

* `HELLO`
* `WELCOME`
* `ABORT`
* `CHALLENGE`
* `AUTHENTICATE`
* `GOODBYE`
* `PUBLISHED`
* `SUBSCRIBE`
* `SUBSCRIBED`
* `UNSUBSCRIBE`
* `UNSUBSCRIBED`
* `EVENT_RECEIVED`
* `CANCEL`
* `REGISTER`
* `REGISTERED`
* `UNREGISTER`
* `UNREGISTERED`
* `INTERRUPT`

----

In my eyes, above distinction and grouping makes a lot of sense ... it minimizes the presence of `Arguments|list, ArgumentsKw|dict` to a the messages which are actually carrying application payloads for the core WAMP actions of RPC and PubSub.

Personally, even though I understand your arguments above, I think the price to pay (in terms of protocol change, and in terms of "complexity") is too high for the potential gain (being able to transport app payload as part of ABORT and having that app payload under those AP mechanisms rather than just as a custom attribute in `ABORT.Details|dict`)

I'll move the issue label to "needs consensus". Lets see how a vote goes ...

**Comment by ecorm** [comment]
@konsultaner , do you have an actual use case where sensitive information needs to be encrypted and passed via an `ABORT` message?

Let's consider when an ABORT is used:
- Authentication failures
- Peer needs to shutdown ASAP and doesn't want to wait for a GOODBYE exchange
- Forcefully killing a session via the meta API
- Protocol violations (some implementations will just disconnect without sending an ABORT)

I don't see a need to pass sensitive information in any of the above situations.

Personally, the only problem I have with ABORT lacking a payload is at the client/router implementation code level, where it's not consistent with the way additional information is passed on to ERROR messages.

My vote is tentatively "no" unless a real-world use case is provided.

**Comment by konsultaner** [comment]
@ecorm I came up with this idea because I do have a usecase for it. I do need the zero-copy capabilities to send a user specific document and some additional information to users that have been locked out from our service. It is very handy that a locked user does authenticate for this information with correct user and password. So i dont want to give the locked user access to the service, but to personalized information about why one was locked and how to unlock again. I know that this is possible in other ways but having a payload would be much easier. At the moment i use the message dict to send a token that is userd to download the personalized information. Very unhandy and indirect. I'm open to better ideas.

**Comment by KSDaemon** [comment]
Let's have a look at this from a different angle: what is the payload? For whom is it intended? The same question may be raised regarding the WAMP message options/details dictionary.

Payload is generated by one peer such as Publisher or Caller or Callee and is intended for another peer such as Subscriber or Callee or Caller.

Options/Details dictionary on the other hand is intended to be used by all peers including router roles like Broker or Dealer because it is supposed to carry service/additional information about the WAMP action itself (like invocation_policy or progressive options) or about payload (like e2ee options).

WAMP Features like e2ee or transparent payload make sense only in the context of communication between client peers and WAMP routers are supposed not to dig into the payload of such communication (e.g. e2ee is especially here to prevent any mitm payload reading even by routers).

WAMP messages like... actually most of WAMP messages that do not have a payload are intended to be used between client peer and WAMP router. I mean there is no further flow (to other peers) when the message is delivered to the router or client peer. So in such cases advanced WAMP features like e2ee or transparent payload don't make sense at all. Indeed, what is the reason to use e2ee between the router and the client if there are no more peers between (assuming you are using secure transport like TLS)? - No reason. Thus you can send any data in dictionaries and not lose anything (in terms of security, transparency, etc)

The only sensible point here is `zero-copy routing` that @konsultaner is mentioning. But this I think highly depends on the implementation and specific app needs. 

@konsultaner Can you elaborate more on your use case? Cause from what I understand: 
* All users are authenticated
* There is a flow in the system when for some reason the authenticated user needs to be locked (kicked) providing some user-specific information.

If I understand you correctly - you are trying to achieve this by killing two birds with one stone: by sending ABORT with user-sensitive data. And that is why you need payload in the ABORT. Right?

But who is locking the user? Can you send a regular EVENT to the user-specific topic or call the RPC registered by the client with that sensitive information and right after that ABORT the user session? Yeah, it is one (or two if you want to ack) WAMP messages more, but everything is used as it was intended: you have a payload flow between end peers with all the available features and options, and then just make a service ABORT message. Why this is not working for you? The WAMP Spec guarantees the order of the messages, so if you send an EVENT and then ABORT - ABORT will never hit the client peer first.

**Comment by oberstet** [comment]
Lot's of good feedback above! I feel like the discussion - now aimed at cost/benefit tradeoffs and how implementers look at this via a vote - is finally appearing to conclude.

> one more sidenote: the `EVENT_RECEIVED` message I mentioned above is a custom Autobahn WAMP message, pls see https://github.com/crossbario/autobahn-python/blob/359f868f9db410586cf01c071220994d8d7f165a/autobahn/wamp/message.py#L3873 - one could argue that (should such a message be of interest ... the message allow for _transactional_ PubSub), then the current message format (as used in Autobahn) lacks `Args, KwArgs` .. but that's a different discussion;)

**Comment by ecorm** [comment]
> Can you send a regular EVENT to the user-specific topic or call the RPC registered by the client with that sensitive information and right after that ABORT the user session?

The client would need to subscribe or register first before receiving that private message. The logic on the router side would not be simple:
- Allow client to authenticate
- Wait for client to subscribe or register a specific topic/procedure, and no other
- Send the private message message to the client via EVENT or CALL.
- Send an ABORT
- In the meantime, don't allow the client to do anything else, or linger too long

Seems pretty convoluted to me, to be honest.

**Comment by KSDaemon** [comment]
If the ABORT message is happening during the connection establishing (not when the session is already opened): then I do not understand from where the problem of zero-copying raises as the message needs to be constructed from the ground :)

**Comment by KSDaemon** [comment]
For the case when locking is done during the session lifetime - I don't see a problem for the client to register an RPC or subscribe to some special topic.

**Comment by ecorm** [comment]
> So i dont want to give the locked user access to the service, but to personalized information about why one was locked and how to unlock again.

@konsultaner I there a reason why that personalized information can't be encrypted/included as a property in the ABORT.Options dictionary? Please note that I'm not terribly familiar with the E2E encryption and payload passthrough features of WAMP.

> If the ABORT message is happening during the connection establishing (not when the session is already opened): then I do not understand from where the problem of zero-copying raises as the message needs to be constructed from the ground :)

@KSDaemon, this is the first time I'm seeing the term _zero-copying_. Is this part of an advanced WAMP feature I'm not aware of?

The contents of the ABORT message in his use case could have originated from a dynamic authenticator that runs on a separate host than the WAMP router.

**Comment by ecorm** [comment]
I now abstain from voting, as @konsultaner presented a compelling use case, but I am not well-versed enough in the E2E and passload passthrough advanced features of WAMP.

**Comment by KSDaemon** [comment]
@ecorm term `zero-copying` is mentioned here by @konsultaner in the context of his implementation. AFAIK there is no such term in the WAMP Spec itself...

Regarding E2EE: Of course sensitive data can be encrypted and putted into dictionary by the app specific way. But that just would not be the e2ee wamp feature flow.

**Comment by oberstet** [comment]
fwiw, rgd E2E and such, regular WAMP decouples clients from payload

* transports
* framing
* encoding

E2E still decouples clients from payload

* transports
* framing

but no longer "encoding", since the app payload is encrypted (end-to-end) and obviously cannot be re-encoded.

On the plus side, clients do not need to trust routers for payload

* confidentiality
* authenticity
* integrity

but still for "availability" (for general routing availability, independent of specific message payload).

**Comment by konsultaner** [comment]
Wow, thanks for the great feedback. I will comment on it on monday!

**Comment by konsultaner** [comment]
I want to anwser on as many arguments as possible. But I might miss some.

@ecorm said:

> WAMP messages like... actually most of WAMP messages that do not have a payload are intended to be used between client peer and WAMP router. I mean there is no further flow (to other peers) when the message is delivered to the router or client peer. So in such cases advanced WAMP features like e2ee or transparent payload don't make sense at all. Indeed, what is the reason to use e2ee between the router and the client if there are no more peers between (assuming you are using secure transport like TLS)? - No reason. Thus you can send any data in dictionaries and not lose anything (in terms of security, transparency, etc)

It is not defined that the actual handling of authentications is done by the router itself. In my system that is running in a production environment, the actual authenticator is a client. This is due to network security. The router is located in the [DMZ](https://en.wikipedia.org/wiki/DMZ_(computing)) and all clients are not accessible from the WAN endpoint. routing the `ABORT` would allow E2EE and would make sense.

Zero-Copy is not defined in the specs, because it has nothing to do with the protocol itself. It simply means that only routing information is unserialized to the applications heap-memory. When routing bigger datasets, 1MB or more, this makes a massive difference in transaction performance. CPU and memory.

> If I understand you correctly - you are trying to achieve this by killing two birds with one stone: by sending ABORT with user-sensitive data. And that is why you need payload in the ABORT. Right?
>
>But who is locking the user? Can you send a regular EVENT to the user-specific topic or call the RPC registered by the client with that sensitive information and right after that ABORT the user session? Yeah, it is one (or two if you want to ack) WAMP messages more, but everything is used as it was intended: you have a payload flow between end peers with all the available features and options, and then just make a service ABORT message. Why this is not working for you? The WAMP Spec guarantees the order of the messages, so if you send an EVENT and then ABORT - ABORT will never hit the client peer first.

My scenario is a Saas solution running on WAMP. The user basically is locked by the company running the service. They have a backend that allows them to lock a user, that is one of their clients. The next time a user wants to log in, a dialog will open telling that a login is not possible. I want to tell the user why and/or send some documents that need to be filled and/or present some images. Basically some assets.

Sending an event is not possible, because the user might not be logged in.

```mermaid
sequenceDiagram
    participant Client
    participant Router
    participant Authenticator
    
    Client->>Router: HELLO
    Router->>Authenticator: HELLO
    Authenticator-->>Router: [ABORT,{message:"Locked User"},[],{reason:"Payment Issues",newSepa: "ahdjhjksa=/base64"}
    Router-->>Client: [ABORT,{message:"Locked User"},[],{reason:"Payment Issues",newSepa: "ahdjhjksa=/base64"}
```

Maybe that mermaid diagram makes it a little clearer.?

> Can you send a regular EVENT to the user-specific topic or call the RPC registered by the client with that sensitive information and right after that ABORT the user session?

As @ecorm mentioned. That would be a very complex thing to do, since you need to give the client that is locked an actual session.

@KSDaemon 
> If the ABORT message is happening during the connection establishing (not when the session is already opened): then I do not understand from where the problem of zero-copying raises as the message needs to be constructed from the ground :)

This is not true. File handles can be zero-copied as well and passed into the network-buffer directly. That means there is not need to put them into the application heap. This requires using a binary compatible message format, but it thats it. So using JSON doesn't work, but msgpack is just fine. At this point the opaque payload featues comes in place. For me it is mostly interesting, because the router doesn't create the message, but another client that is the actual authenticator.

Since I opened this issues, I am obviously +1 for it. Here are a couple more arguments for it:

1. Error has `args` and `kwargs`. The major difference is that `ABORT` is part of the authentication process and `ERROR` is used for errors within the session scope.
2. Implementing `args` and `kwargs` is a one-liner in my code. I would simply extend my `Abort` from `AbstractMessageWithPayload` instead of `AbstractMessage`. Works like charm. So I thinks this shouldn't make a lot of trouble in other implementations.
3. It is backward compatible. All messages with payload are allowed to be send without `args` and `kwargs`

I hope I made my point a little clearer and didn't forget anything :)

**Comment by ecorm** [comment]
> @ecorm said:
>
> >    WAMP messages like... actually most of WAMP messages that do not have a payload are intended to be used between client peer and WAMP router.

Probably just a copy/paste error on your part, but it was @KSDaemon who wrote that. :-)

> Maybe that mermaid diagram makes it a little clearer.?

That's not how dynamic authentication is supposed to work. It's supposed to be an RPC on the authenticator's side, with the CALL initiated by the router. It is a protocol error for WAMP clients to receive HELLO messages.

But you've nonetheless convinced me that ABORT needs payload fields, because you've demonstrated a use case where complex data needs to be sent back from the dynamic authenticator (e.g. service subscription renewal details, lost password recovery) to the front-end client via an ABORT message, and that complex data needs to be E2E encrypted. In your use case, the user is actually authentic, but is locked out of using any services on the realm.

It's not clear if WAMP allows implementations to use `ABORT.Options` properties freely other than `ABORT.Options.message`. There is the custom Options proposal #345, but I think that should be only for WAMP implementations to extend the protocol in some proprietary manner, not for clients to exchange application-level information.

Since implementations would already have machinery in place to perform E2E encryption on payloads for other messages, it makes sense and is more consistent for ABORT to have payload fields than can be similarly encrypted (versus just one or a set of arbitrary fields buried in the `ABORT|Options dictionary)`.

I'm now +1 in your proposal to add payload fields to ABORT.

**Comment by konsultaner** [comment]
@KSDaemon @oberstet any changes of you votes?

**Comment by KSDaemon** [comment]
Thanks @konsultaner for explaining! That makes sense! 

I carefully read all points and I'm +1 on adding payload options to the `ABORT` message.

Pros from my side:
* We have a real production sensible case
* It is easy to add
* It is backward compatible
* It will be aligned with `ERROR` (which has payload). (Cause under some angle ABORT can be treated in the same manner as `ERROR`)

One note regarding E2EE in the ABORT messages - that can work only if both end peers has the same shared secret. 'Cause in other cases it won't work due to necessity to obtain a secret via some RPC, but that is not possible as there is no WAMP session established yet.

**Comment by ecorm** [comment]
> One note regarding E2EE in the ABORT messages - that can work only if both end peers has the same shared secret. 'Cause in other cases it won't work due to necessity to obtain a secret via some RPC, but that is not possible as there is no WAMP session established yet.

The dynamic authenticator (a separate client) is the other end in konsultaner's use case, so I don't see why they can't exchange keys during the authentication process without the router needing to know any secrets.

**Comment by ecorm** [comment]
> If then authenticator decides to decline the client and sends an ABORT message with an encrypted payload - there is no way for the client to obtain the used encryption key (aka secret).

I suppose part of the ABORT payload (some keyword arg) could be left unencrypted to exchange the information that would have otherwise been part of the WELCOME message, then the remaining part of the ABORT payload would contain the sensitive encrypted information.

But this breaks the goal of the router treating all payloads the same regardless of the message they're bundled in. :frowning_face:

It's good that we're analyzing this and trying to think it through.

**Comment by ecorm** [comment]
> If then authenticator decides to decline the client and sends an ABORT message with an encrypted payload - there is no way for the client to obtain the used encryption key (aka secret).

But there's no need for the client to communicate back encrypted information via the router after it receives an ABORT, as the session is ended as that point. If we're talking about public key cryptography, only the client needs to send it's public key as part of the HELLO message.

```mermaid
sequenceDiagram
    participant Client
    participant Router
    participant Authenticator
    
    Client->>Router: HELLO
    Router->>Authenticator: CALL("authenticate", authinfo, pubkey)
    Authenticator->>Router: RESULT("wamp.error.authentication_suspended",<br>args=[encrypted_with_pubkey])
    Router->>Client: ABORT("wamp.error.authentication_suspended",<br>args=[encrypted_with_pubkey])
```

**Comment by konsultaner** [comment]
@oberstet what do you think about it? PR or do you stick to a no?

**Comment by oberstet** [comment]
actually, I agree with @ecorm 

> But you've nonetheless convinced me that ABORT needs payload fields, because you've demonstrated a use case where complex data needs to be sent back from the dynamic authenticator (e.g. service subscription renewal details, lost password recovery) to the front-end client via an ABORT message, and that complex data needs to be E2E encrypted. 

so, yeah, it is an invasive change (allow args, kwargs), but the use case is pretty compelling ... IOW: I am +1;)

**Comment by konsultaner** [comment]
I will try to provide a PR then 😇
