### ISSUE TITLE
Equivalent of 500 Internal Server Error in WAMP

### ISSUE THREAD

**Issue by om26er** [wamp-proto/wamp-proto#505]
### The context here is a microservice and NOT the router

What is the equivalent WAMP error URI that a microservice should use when it needs to convey an internal error within the context of that microservice. For example if the service cannot connect to the database, or if the service is misconfigured

**Comment by ecorm** [comment]
As I understand it, applications can define their own error URIs, as long as they don't start with `wamp.`.

For example:
- `myapp.cannot_connect_to_database`
- `myapp.service_is_misconfigured`

You could even use HTTP status codes if you wanted to:

-`myapp.status.500.internal_server_error`

In our proprietary app, we return custom error URIs all the time from RPCs via the Crossbar WAMP router, and the latter never complained. We try to reuse the same set of custom URIs as much as possible.

You could have an error URI "namespace" for each microservice, if you wanted to:
- `myapp.service_1.some_error`
- `myapp.service_1.some_other_error`
- `myapp.service_2.some_error`

[Section 6.2.6 Call ERROR](https://wamp-proto.org/wamp_latest_ietf.html#name-call-error) of the spec even shows an example with an application-specific error URI:

`[8, 48, 7814135, {}, "com.myapp.error.object_write_protected", ["Object is write protected."], {"severity": 3}]`

There are no standard URIs for application-level or database stuff in the WAMP specification. Nor should there be, in my humble opinion.

**Comment by om26er** [comment]
@ecorm ok, that essentially answers what I was looking for. I main wanted to know if there were recommended errors URIs that microserivces could depend on and as you said using custom URIs is the way to go. So I am going to close this one, thanks

**Comment by oberstet** [comment]
> There are no standard URIs for application-level or database stuff in the WAMP specification. Nor should there be, in my humble opinion.

fwiw, I'd agree. if we can manage to properly define error URIs in WAMP for only protocol related stuff, and manage to make it happen and interop between different implementations (both clients and routers), that would be perfect and a good achievement I would add.

**Comment by KSDaemon** [comment]
Don't you think we are on exact that way? We defined the `wamp.` prefix for Error URIs which should be used only internally by wamp implementations for protocol-related error.

IDK, does it make sense if implementations would not even allow `wamp.`-prefixed errors from the client side? Look a bit strange: client throws and error, but the error begins with `wamp.` - so such code call should be errored %)

**Comment by oberstet** [comment]
> Don't you think we are on exact that way? 

First of all, given the resources we have we have done a fantastic job! Also because in the recent months, you guys have been contributing a lot of work =) \-/ !

As a paranoid perfectionist I would say: it is still far from perfect;) We don't have automated tests which demonstrate interop between different implementation, we don't have a formally defined model of WAMP. 

>  does it make sense if implementations would not even allow wamp.-prefixed errors from the client side?

`wamp.` prefixed errors are a) WAMP protocol handling itself related, and b) WAMP specification defined

thus, clients and routers must use those URIs as specified - and only as such.

a client that uses a new `wamp.` prefixed error URI which is _not_ defined in the spec is misbehaving.

a client that uses a spec defined `wamp.` prefixed error URI _not_ in the way the spec defines is misbehaving.

how should a WAMP peer (client or router) behave when it recognizes behavior of the peer that doesn't conform to the spec (it "misbehaves")?

in general, I can see 2 ways one could motivate a design:

1. protect itself and the user from the other peer
2. support the developer/admin of the misbehaving peer to improve it's implementation/configuration

following 1. would motivate:

immediately kill/terminate the peer connection, and (potentially) only log this fact

following 2.:

try to only notify/inform the peer, but keep the connection/session open and do the best to "keep things together", and try to behave as likely intended by the _app_ developer

with Crossbar.io, I have primarily followed 1. - a misbehaving peer is broken, and talking to a broken peer is an additional risk because it might trigger code paths in oneself which never were tested or designed to work, so unknown/unexpected things will pile up ..
