### ISSUE TITLE
WebSocket subprotocol registry

### ISSUE THREAD

**Issue by darkl** [wamp-proto/wamp-proto#78]
Since WAMPv2, the subprotocol name changed to "wamp.2.json"/"wamp.2.msgpack". (| ".batched")

The protocol should be re-registered [here](http://www.iana.org/assignments/websocket/websocket.xml#subprotocol-name) under the new names, so it will still be an officially registered subprotocol.

**Comment by goeddea** [comment]
see http://tools.ietf.org/html/rfc5226 for the process to use

**Comment by oberstet** [comment]
Since we have to encode the serializer wished for in the WebSocket subprotocol identifier, we would need to file for new subprotocol IDs with the IETF every time we add a new serializer. Eg Crossbar.io now supports:

* `json`
* `msgpack`
* `cbor`
* `ubjson`

Multiply that with `batched` vs unbatched (default), plus the original `wamp` (means unbatched JSON) this would mean we would now need 9 subprotocol identifiers.

I'm not sure this is sustainable .. and practically, it doesn't matter: I doubt anyone will use a subprotocol identifier starting with `wamp..` as a prefix. By chance or by purpose.

I guess it'll pop up again the latest when we carry this spec to the IETF again. So I leave it open ..

**Comment by oberstet** [comment]
closing: lets see if IETF number registry is complaining. practically speaking, it has never been a problem ..
